# Generated by Django 3.2.6 on 2021-08-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopHome', '0003_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
